# ──────────────────────────────────────────────────────────────────────────────
# Stage 1: Builder — install dependencies into a clean layer
# ──────────────────────────────────────────────────────────────────────────────
FROM python:3.11-slim AS builder

WORKDIR /install

# Install OS-level build tools needed to compile faiss-cpu wheels
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies in an isolated layer.
# By copying requirements.txt first (before source code), Docker can cache this
# expensive step and skip it on rebuilds if only source code changed.
COPY requirements.txt .
RUN pip install --prefix=/install/deps --no-cache-dir -r requirements.txt


# ──────────────────────────────────────────────────────────────────────────────
# Stage 2: Runtime — lean final image with no build tools
# ──────────────────────────────────────────────────────────────────────────────
FROM python:3.11-slim

WORKDIR /app

# Copy installed packages from builder (keeps final image ~200MB smaller)
COPY --from=builder /install/deps /usr/local

# Copy application source code
COPY app/     ./app/
COPY data/    ./data/

# data/ must contain the three files generated by the Colab notebook:
#   data/faiss_index.bin   — FAISS vector index
#   data/gmm_model.pkl     — trained GMM fuzzy clustering model
#   data/corpus.pkl        — documents + labels

# Environment: don't buffer stdout (so logs appear in real time in docker logs)
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# The fastembed model cache lives here inside the container.
# Mount a volume over this path to avoid re-downloading on every container start:
#   docker run -v fastembed_cache:/root/.cache/fastembed ...
ENV FASTEMBED_CACHE_DIR=/root/.cache/fastembed

EXPOSE 8000

# Start uvicorn pointing at app/main.py::app
#   --workers 1   : single worker is fine since the cache is in-memory per-process
#   --host 0.0.0.0: bind to all interfaces so the port is reachable outside the container
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
