import pickle
import faiss
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.responses import RedirectResponse
from pydantic import BaseModel

from app.embedder import embed_query
from app.clustering import FuzzyCluster
from app.cache import SemanticCache
from app.config import CACHE_SIMILARITY_THRESHOLD

app = FastAPI(title="Semantic Cache Search API")

# ---------------------------------------------------------------------------
# Load pre-built artefacts generated by the Colab notebook (Implementation.md)
# Place these files in the data/ directory before starting the server:
#   data/faiss_index.bin  — FAISS vector index
#   data/gmm_model.pkl    — trained GMM fuzzy clustering model
#   data/corpus.pkl       — {"documents": [...], "labels": [...]}
# ---------------------------------------------------------------------------
try:
    _index = faiss.read_index("data/faiss_index.bin")

    with open("data/gmm_model.pkl", "rb") as f:
        _gmm = pickle.load(f)

    with open("data/corpus.pkl", "rb") as f:
        _corpus = pickle.load(f)
    _documents = _corpus["documents"]
    _labels    = _corpus["labels"]

    print(f"Loaded FAISS index  : {_index.ntotal:,} vectors")
    print(f"Loaded GMM model    : {_gmm.n_components} clusters")
    print(f"Loaded corpus       : {len(_documents):,} documents")

except FileNotFoundError as e:
    raise RuntimeError(
        f"Missing data file: {e}. "
        "Please run the Colab notebook (Implementation.md) and place the "
        "downloaded files in the data/ directory."
    )

cache = SemanticCache(similarity_threshold=CACHE_SIMILARITY_THRESHOLD)


class QueryRequest(BaseModel):
    query: str


@app.get("/", include_in_schema=False)
def root():
    """Redirect base URL to interactive API docs."""
    return RedirectResponse(url="/docs")

def _dominant_cluster(embedding: np.ndarray) -> int:
    """Return the index of the cluster with the highest GMM probability."""
    probs = _gmm.predict_proba(embedding.reshape(1, -1))[0]
    return int(np.argmax(probs))


@app.post("/query")
def query_endpoint(request: QueryRequest):
    query = request.query

    # Embed the incoming query (fastembed — no PyTorch, no DLL issues)
    q_emb = embed_query(query)                        # shape (384,)
    q_emb_norm = q_emb.copy()
    faiss.normalize_L2(q_emb_norm.reshape(1, -1))

    # 1. Check semantic cache first
    cache_result = cache.lookup(q_emb_norm)
    if cache_result:
        return {"query": query, **cache_result}

    # 2. Cache miss — vector search in FAISS
    D, I = _index.search(q_emb_norm.reshape(1, -1), k=3)

    top_results = []
    for score, idx in zip(D[0], I[0]):
        top_results.append({
            "text":  _documents[idx][:500],
            "label": _labels[idx] if isinstance(_labels[idx], str)
                     else _labels[int(_labels[idx])],   # handle int targets
            "similarity": float(score),
        })

    dominant = _dominant_cluster(q_emb_norm)
    result_text = top_results[0]["text"] if top_results else ""

    cache.store(query, q_emb_norm, result_text, dominant)

    return {
        "query":            query,
        "cache_hit":        False,
        "matched_query":    None,
        "similarity_score": None,
        "result":           top_results,
        "dominant_cluster": dominant,
    }


@app.get("/cache/stats")
def cache_stats():
    return cache.stats()


@app.delete("/cache")
def clear_cache():
    cache.clear()
    return {"message": "Cache cleared successfully."}
